version: '3.8'
services:
  dev-db:
    image: postgres:13.2
    ports:
      - 9000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data